# Generated by Django 4.0 on 2021-12-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
